// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;

import com.bdb.Column;
import com.bdb.Relation;

public class RelDecl extends Decl_rel {

    final public static int ARG_LENGTH = 2 ;
    final public static int TOK_LENGTH = 5 ;

    public void execute () {
        super.execute();
        Relation rel = Relation.getRelation(getRel_name().toString().trim());
        if(null==rel)
            createNewRelation();
        else
            System.err.println("Table with the name " + rel.getName() + " already exists");
    }

    public void createNewRelation(){
        String name = getRel_name().toString().trim();
        AstCursor c = new AstCursor();
        int index = 0;
        int numOfColumns = 0;

        for (c.FirstElement(getFld_decl_list()); c.MoreElement(); c.NextElement() ) {
            numOfColumns += 1;
        }

        Column [] columns = new Column[numOfColumns];
        numOfColumns = 0;     //reusing the variable
        for (c.FirstElement(getFld_decl_list()); c.MoreElement(); c.NextElement() ) {
            AstNode node = c.node ;
            String cl_type = node.arg[1].toString().trim();
            String cl_name = node.arg[0].toString().trim();
            if(!(cl_type.equals("int") || cl_type.equals("str"))){
                System.err.println("Invalid Datatype: datatype not supported");
                return;
            }
            columns[numOfColumns] = new Column(cl_type, cl_name, numOfColumns);
            numOfColumns += 1;
        }
        Relation relation = new Relation(name, numOfColumns, columns);
        relation.create();
    }

    public AstToken getCREATE () {
        
        return (AstToken) tok [0] ;
    }

    public Fld_decl_list getFld_decl_list () {
        
        return (Fld_decl_list) arg [1] ;
    }

    public AstToken getLP () {
        
        return (AstToken) tok [2] ;
    }

    public AstToken getRP () {
        
        return (AstToken) tok [3] ;
    }

    public Rel_name getRel_name () {
        
        return (Rel_name) arg [0] ;
    }

    public AstToken getSEMI () {
        
        return (AstToken) tok [4] ;
    }

    public AstToken getTABLE () {
        
        return (AstToken) tok [1] ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {true, true, false, true, false, true, true} ;
    }

    public RelDecl setParms
    (AstToken tok0, AstToken tok1, Rel_name arg0, AstToken tok2, Fld_decl_list arg1, AstToken tok3, AstToken tok4)
    {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        tok [0] = tok0 ;            /* CREATE */
        tok [1] = tok1 ;            /* TABLE */
        arg [0] = arg0 ;            /* Rel_name */
        tok [2] = tok2 ;            /* LP */
        arg [1] = arg1 ;            /* Fld_decl_list */
        tok [3] = tok3 ;            /* RP */
        tok [4] = tok4 ;            /* SEMI */
        
        InitChildren () ;
        return (RelDecl) this ;
    }

}
