// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;

import com.bdb.DbClient;
import com.bdb.Tuple;

import java.util.List;

public class ShowDb extends Show {

    final public static int ARG_LENGTH = 1 /* Kludge! */ ;
    final public static int TOK_LENGTH = 2 ;

    public void execute () {
        
        super.execute();
        selectStar();
    }

    public void selectStar(){
        DbClient dbClient = new DbClient("mydbenv", "metadata");
        List<Tuple> tupleList = dbClient.selectStarFromRelation();
        System.out.println(tupleList.size() + "records found. \n");
        for(Tuple tuple : tupleList)
            System.out.println(tuple +"\n" );
    }


    public AstToken getSEMI () {
        
        return (AstToken) tok [1] ;
    }

    public AstToken getSHOW () {
        
        return (AstToken) tok [0] ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {true, true} ;
    }

    public ShowDb setParms (AstToken tok0, AstToken tok1) {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        tok [0] = tok0 ;            /* SHOW */
        tok [1] = tok1 ;            /* SEMI */
        
        InitChildren () ;
        return (ShowDb) this ;
    }

}
