// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;

import com.bdb.MyDatabaseException;
import com.bdb.Relation;

public class ShowRel extends Show {

    final public static int ARG_LENGTH = 1 ;
    final public static int TOK_LENGTH = 2 ;

    public void execute () {
        
        super.execute();

        showRelationInformation();

    }

    public void showRelationInformation(){
        Relation rel = Relation.getRelation(getRel_name().toString().trim());
        if(null != rel)
            rel.showRelation();
        else{
            try{
                throw new MyDatabaseException("Relation doesn't exist");
            }catch (MyDatabaseException mdbe){
                mdbe.printStackTrace();
            }
        }
    }

    public Rel_name getRel_name () {
        return (Rel_name) arg [0] ;
    }

    public AstToken getSEMI () {
        
        return (AstToken) tok [1] ;
    }

    public AstToken getSHOW () {
        
        return (AstToken) tok [0] ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {true, false, true} ;
    }

    public ShowRel setParms (AstToken tok0, Rel_name arg0, AstToken tok1) {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        tok [0] = tok0 ;            /* SHOW */
        arg [0] = arg0 ;            /* Rel_name */
        tok [1] = tok1 ;            /* SEMI */
        
        InitChildren () ;
        return (ShowRel) this ;
    }

}
